language: ruby

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - ree
  - rbx-18mode
  - rbx-19mode

jdk:
  - oraclejdk7
  - openjdk7

env: CI="travis"

notifications:
  email: false
  flowdock: 1da4416b8ff98d1880986472428b1b1b

branches:
  only:
    - master
    - 2.x-stable

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  exclude:
    - rvm: 1.8.7
      jdk: openjdk7
    - rvm: 1.9.2
      jdk: openjdk7
    - rvm: 1.9.3
      jdk: openjdk7
    - rmv: 2.0.0
      jdk: openjdk7
    - rvm: ruby-head
      jdk: openjdk7
    - rvm: ree
      jdk: openjdk7
    - rvm: rbx-18mode
      jdk: openjdk7
    - rvm: rbx-19mode
      jdk: openjdk7
