language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby
  - rbx-18mode
  - rbx-19mode
jdk:
  - oraclejdk7
  - openjdk7
matrix:
  exclude:
    - rvm: 1.8.7
      jdk: openjdk7
    - rvm: 1.8.7
      jdk: oraclejdk7
    - rvm: 1.9.2
      jdk: openjdk7
    - rvm: 1.9.2
      jdk: oraclejdk7
    - rvm: 1.9.3
      jdk: openjdk7
    - rvm: 1.9.3
      jdk: oraclejdk7
    - rvm: 2.0.0
      jdk: openjdk7
    - rvm: 2.0.0
      jdk: oraclejdk7
    - rvm: rbx-18mode
      jdk: openjdk7
    - rvm: rbx-19mode
      jdk: oraclejdk7
env: JRUBY_OPTS="--server -Xcompile.invokedynamic=false -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-noverify -J-Xms512m -J-Xmx1024m"
