language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby
  - ree
jdk:
  - oraclejdk7
  - openjdk7
matrix:
  exclude:
    - rvm: 1.8.7
      jdk: openjdk7
    - rvm: 1.8.7
      jdk: oraclejdk7
    - rvm: 1.9.2
      jdk: openjdk7
    - rvm: 1.9.2
      jdk: oraclejdk7
    - rvm: 1.9.3
      jdk: openjdk7
    - rvm: 1.9.3
      jdk: oraclejdk7
    - rvm: 2.0.0
      jdk: openjdk7
    - rvm: 2.0.0
      jdk: oraclejdk7
    - rvm: ree
      jdk: openjdk7
    - rvm: ree
      jdk: oraclejdk7
